### ISSUE TITLE
mod keeps crashing once I run it, even on latest version

### ISSUE THREAD

**Issue by Exploderus** [Slexom/earth2java#104]
i tried running this mod on my modpack, however I kept getting the following error: java.lang.reflect.InvocationTargetException: null. i tried running it on 1.19.4 and it still gives me this error. it's been a recurring problem even for other people and it definitely needs to be fixed.
![Schermata 2023-05-10 alle 14 45 36](https://github.com/Slexom/earth2java/assets/133120713/413d5f8a-4f4d-4c0b-b925-bb2433ba97d5)

**Comment by Exploderus** [comment]
apologies for the wait, i ran my modpack again so I could get the logs, here they are:

---- Minecraft Crash Report ----
// Sorry :(

Time: 2023-05-13 11:58:50
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.0-universal.jar%23285!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.0-universal.jar%23285!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23280!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD earthtojavamobs --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23282!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23281!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
		at slexom.earthtojava.forge.Earth2JavaModForge.<init>(Earth2JavaModForge.java:26) ~[earthtojavamobs-forge-mc1.19.2-1.9.3+1.19.2.jar%23235!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23282!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23281!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /Users/mac/Documents/curseforge/minecraft/Instances/AntoCraft/mods/earthtojavamobs-forge-mc1.19.2-1.9.3+1.19.2.jar
	Failure message: Earth2Java (earthtojavamobs) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.9.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at slexom.earthtojava.forge.Earth2JavaModForge.<init>(Earth2JavaModForge.java:26) ~[earthtojavamobs-forge-mc1.19.2-1.9.3+1.19.2.jar%23235!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23282!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23281!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 11.6.8
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 297274032 bytes (283 MiB) / 1560281088 bytes (1488 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel Iris Plus Graphics 640
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x5926
	Graphics card #0 versionInfo: Revision ID: 0x0006
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4 SO-DIMM
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4 SO-DIMM
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 5445.25
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 6.00
	JVM Flags: 3 total; -Xss1M -Xmx4096m -Xms256m
	Loaded Shaderpack: (off)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
	Mod List: 
		elytraslot-forge-6.1.1+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.1.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		blue_skies-1.19.2-1.3.20.jar                      |Blue Skies                    |blue_skies                    |1.3.20              |COMMON_SET|Manifest: NOSIGNATURE
		Fastload-Reforged-2.6.9+1.19.2.jar                |Fastload                      |fastload                      |2.6.9+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		infernal-expansion-1.19.2-2.5.3.jar               |Infernal Expansion            |infernalexp                   |2.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		nether-s-exoticism-1.19.2-1.2.4.jar               |Nether's Exoticism            |nethers_exoticism             |1.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1015.jar                  |Just Enough Items             |jei                           |11.6.0.1015         |COMMON_SET|Manifest: NOSIGNATURE
		allay-forge-1.19.1-4.1.1.jar                      |Allay Mod                     |allay                         |4.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		naturalist-forge-3.0.2-1.19.2.jar                 |Naturalist                    |naturalist                    |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		AttributeFix-Forge-1.19.2-17.2.6.jar              |AttributeFix                  |attributefix                  |17.2.6              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		the-conjurer-1.19.2-1.1.5.jar                     |The Conjurer                  |conjurer_illager              |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		goodall-1.2.0-forge.jar                           |Goodall                       |goodall                       |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		DoggyTalents-1.19.2-2.6.10.jar                    |Doggy Talents 2               |doggytalents                  |2.6.10              |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		macawsbridgesbyg-1.19.2-1.2.jar                   |Macaw's Bridges - BYG         |macawsbridgesbyg              |1.19.2-1.2          |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.6.2a.jar                               |Rubidium                      |rubidium                      |0.6.2a              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.0.jar                 |Waystones                     |waystones                     |11.4.0              |COMMON_SET|Manifest: NOSIGNATURE
		duckling-2.0.8-forge.jar                          |Duckling                      |duckling                      |2.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.3-1.19.jar                            |Citadel                       |citadel                       |2.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.18.jar                |Bookshelf                     |bookshelf                     |16.2.18             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.19.2-1.5.5.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.5        |COMMON_SET|Manifest: NOSIGNATURE
		everycomp-1.19.2-2.4.4.jar                        |Every Compat                  |everycomp                     |1.19.2-2.4.4        |COMMON_SET|Manifest: NOSIGNATURE
		takesapillage-1.0.3-1.19.2.jar                    |It Takes A Pillage            |takesapillage                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		bygonenether-1.2.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |COMMON_SET|Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.2.jar                        |Blueprint                     |blueprint                     |6.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		savage_and_ravage-1.19.2-5.0.4.jar                |Savage & Ravage               |savage_and_ravage             |5.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		dragonmounts-1.19.2-1.1.4a.jar                    |Dragon Mounts: Legacy         |dragonmounts                  |1.1.4a              |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |COMMON_SET|Manifest: NOSIGNATURE
		Max's Miny Golems.jar                             |Max's Miny Golems             |maxs_miny_golems              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.19.2-1.8.1.jar           |Friends&Foes                  |friendsandfoes                |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.19.2-2.7.2.jar                    |Structure Gel API             |structure_gel                 |2.7.2               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.7-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.1.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.1          |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.31-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.31       |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
		UnusualEnd1.19.2_V1.4.1.jar                       |Unusual End                   |unusualend                    |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		rottencreatures-forge-1.19.2-1.0.1.jar            |Rotten Creatures              |rottencreatures               |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		CNB-1.19-1.5.2.jar                                |Creatures and Beasts          |cnb                           |1.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		tetra-1.19.2-5.2.1.jar                            |Tetra                         |tetra                         |5.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		tetranomicon-1.4.2-1.19.2.jar                     |Tetranomicon                  |tetranomicon                  |1.4.2-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		ecologics-forge-1.19.2-2.1.11.jar                 |Ecologics                     |ecologics                     |2.1.11              |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.4.1_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.19.2-1.2.8a.jar                        |Oculus                        |oculus                        |1.2.8a              |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.4-398.jar                                 |Quark                         |quark                         |3.4-398             |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.3.10.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.10       |COMMON_SET|Manifest: NOSIGNATURE
		EarthMobs-1.19.2-4.4.0.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.19.2-4.4.0        |COMMON_SET|Manifest: NOSIGNATURE
		hunterillager-1.19.2-8.0.0.jar                    |Hunter Illager                |hunterillager                 |1.19.2-8.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.82-forge.jar                     |Architectury                  |architectury                  |6.5.82              |COMMON_SET|Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.19.2-1.6.4.jar              |Biome Makeover                |biomemakeover                 |1.19.2-1.6.4        |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Adorn-3.8.3+1.19.2-forge.jar                      |Adorn                         |adorn                         |3.8.3+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar |Oh The Biomes You'll Go       |byg                           |2.0.0.13            |COMMON_SET|Manifest: NOSIGNATURE
		charmofundying-forge-6.2.0+1.19.2.jar             |Charm of Undying              |charmofundying                |6.2.0+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		EnchantWithMob-1.19.2-7.4.1.jar                   |Enchant With Mob              |enchantwithmob                |1.19.2-7.4.1        |COMMON_SET|Manifest: NOSIGNATURE
		mavapi-1.0.1-mc1.19.2.jar                         |More Axolotl Variants API     |mavapi                        |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		earthtojavamobs-forge-mc1.19.2-1.9.3+1.19.2.jar   |Earth2Java                    |earthtojavamobs               |1.9.3               |ERROR     |Manifest: NOSIGNATURE
		mavm-1.2.0-mc1.19.2.jar                           |More Axolotl Variants Mod     |mavm                          |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		exoticbirds-1.19.2-2.6.0.jar                      |Exotic Birds                  |exoticbirds                   |2.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: e789ed8a-3a3a-469d-bbb5-8fab892c8e79
	FML: 43.2
	Forge: net.minecraftforge:43.2.0

**Comment by Slexom** [comment]
add in hte mod list **[ClothConfig](https://www.curseforge.com/minecraft/mc-mods/cloth-config)** and let me know if still crash. I'm updating CF page for the dependency
