### ISSUE TITLE
Crash when Raid starts in 1.19 version.

### ISSUE THREAD

**Issue by Muffintiem** [Slexom/earth2java#79]
I have no idea why this particular mod is causing crashes whenever a raid starts but that's what's been happening and I can't reload the world until I take this mod out

**Comment by Muffintiem** [comment]
I managed to get a crash report but it mentions nothing about this mod just Architectury, which this mod uses. I tested taking out each mod that uses Architectury individually to make sure which mod it was and that it wasn't being caused directly by the API (if I hadn't gotten any results from removing individual mods I would have taken Architectury and all mods that depend on it and tested that).

---- Minecraft Crash Report ----
// You're mean.

Time: 6/29/22, 2:51 AM
Description: Ticking player

java.lang.ExceptionInInitializerError
	at net.minecraft.class_3765$1.<clinit>(class_3765.java:821)
	at net.minecraft.class_3765.method_20016(class_3765.java:881)
	at net.minecraft.class_3765.<init>(class_3765.java:168)
	at net.minecraft.class_3767.method_16532(class_3767.java:162)
	at net.minecraft.class_3767.method_16540(class_3767.java:127)
	at net.minecraft.class_1294$1.method_5572(class_1294.java:60)
	at net.minecraft.class_1293.method_5589(class_1293.java:188)
	at net.minecraft.class_1293.method_5585(class_1293.java:165)
	at net.minecraft.class_1309.method_6050(class_1309.java:800)
	at net.minecraft.class_1309.method_5670(class_1309.java:440)
	at net.minecraft.class_1297.method_5773(class_1297.java:467)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:485)
	at net.minecraft.class_3244.method_18784(class_3244.java:241)
	at net.minecraft.class_2535.method_10754(class_2535.java:246)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl$1 cannot be cast to class net.minecraft.class_1299 (dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl$1 and net.minecraft.class_1299 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5419f379)
	at net.minecraft.class_3765$class_3766.<clinit>(class_3765.java:86)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3765$1.<clinit>(class_3765.java:821)
	at net.minecraft.class_3765.method_20016(class_3765.java:881)
	at net.minecraft.class_3765.<init>(class_3765.java:168)
	at net.minecraft.class_3767.method_16532(class_3767.java:162)
	at net.minecraft.class_3767.method_16540(class_3767.java:127)
	at net.minecraft.class_1294$1.method_5572(class_1294.java:60)
	at net.minecraft.class_1293.method_5589(class_1293.java:188)
	at net.minecraft.class_1293.method_5585(class_1293.java:165)
	at net.minecraft.class_1309.method_6050(class_1309.java:800)
	at net.minecraft.class_1309.method_5670(class_1309.java:440)
	at net.minecraft.class_1297.method_5773(class_1297.java:467)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 289
	Entity Name: muffintiem
	Entity's Exact location: -527.87, 178.00, 119.79
	Entity's Block location: World: (-528,178,119), Section: (at 0,2,7 in -33,11,7; chunk contains blocks -528,-64,112 to -513,319,127), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:485)
	at net.minecraft.class_3244.method_18784(class_3244.java:241)
	at net.minecraft.class_2535.method_10754(class_2535.java:246)
	at net.minecraft.class_3242.method_14357(class_3242.java:182)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Slexom** [comment]
Released a new version, can you confirm the bug is now fixed?
https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric/files/3853403

**Comment by Muffintiem** [comment]
That seems to have fixed it.
